### ISSUE TITLE
send UIImage

### ISSUE THREAD

**Issue by moh1122** [ewalk40/WatchConnectivityDemo#1]
Hello
Can we send a UIImage instead?
Ive tried but its not working with me, can you please show me how to send a uiimage to Apple Watch.

**Comment by ewalk40** [comment]
Here's what I found, I'll add to the tutorial at a later date, finishing school at the moment.

https://stackoverflow.com/questions/33113823/how-to-transfer-a-uiimage-using-watch-connectivity
