### ISSUE TITLE
Doesn't work on iOS14.1 | Xcode 12.1 | WatchOs 7.0.1

### ISSUE THREAD

**Issue by cosyeah** [ewalk40/WatchConnectivityDemo#2]
It's very weird. These codes is everything work on my simulator but doesn't work on my device.

**Comment by ewalk40** [comment]
Yeah, I wrote it 2 years ago and just never got around to updating it. Apple may have changed how they handle this process on the devices. I'll look into getting you an answer by this weekend.

**Comment by cosyeah** [comment]
> Yeah, I wrote it 2 years ago and just never got around to updating it. Apple may have changed how they handle this process on the devices. I'll look into getting you an answer by this weekend.

Thank for your reply , I've solve the problem last night. Maybe it's bug of Xcode 12.1  , It's work when I switch project's build configuration  from debug to release mode.
